title: Lin Chen's Homepage
page-top-title: Lin Chen
top-section-bg-text: Nanjing University of Information Science and Technology
home-subtitle: Lin Chen&ensp;|&ensp;陈林
copyright-text: '&copy; Haoqian Li 2026; Ref. Sen Li 2023-2026. All Rights Reserved.'
